Assignment_thinhvdph26886/Controllers/BillController.cs
using Assignment_thinhvdph26886.IServices;
using Assignment_thinhvdph26886.Models;
using Assignment_thinhvdph26886.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Assignment_thinhvdph26886.Controllers
{
    public class BillController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IProductServices productServices;
        private readonly IUserServices userServices;
        private readonly ICartDetailServices cartDetailServices;
        private readonly IBillDetailServices billDetailServices;
        private readonly IBillServices billServices;


        public BillController(ILogger<HomeController> logger)
        {
            _logger = logger;
            productServices = new ProductServices();
            userServices = new UserServices();
            cartDetailServices = new CartDetailServices();
            billServices = new BillServices();
            billDetailServices = new BillDetailServices();
        }

        public IActionResult Pay()
        {
            var UserID = userServices.GetUserByName(HttpContext.Session.GetString("username"))[0].UserID;
            var listCartDetails = cartDetailServices.GetAllCartDetails().Where(c => c.UserID == UserID);
            //decimal tongtien = listCartDetails.Sum(c => c.Quantity * c.Product.Price);
            var Chuoi = "";
            var outOfStockProducts = listCartDetails
                             .Where(item => item.Quantity > productServices.GetProductById(item.IDSP).AvailableQuantity)
                             .Select(item => '"' + productServices.GetProductById(item.IDSP).Name);
            Chuoi = string.Join(" ", outOfStockProducts);

            if (listCartDetails.Any())
            {
                if (Chuoi == "")
                {
                    var bill = new Bill()
                    {
                        Id = Guid.NewGuid(),
                        CreateDate = DateTime.Now,
                        UserID = UserID,
                        Status = 1
                    };
                    billServices.CreateBill(bill);
                    var _product = productServices.GetAllProducts();
                    foreach (var item in listCartDetails)
                    {
                        var a = new BillDetails()
                        {
                            Id = Guid.NewGuid(),
                            IdHD = bill.Id,
                            IdSP = item.IDSP,
                            Quantity = item.Quantity,
                            Price = _product.FirstOrDefault(c=>c.ID == item.IDSP).Price,
                        };
                        billDetailServices.CreateBillDetail(a);
                        cartDetailServices.DeleteCartDetail(item.ID);
                        var product = productServices.GetProductById(item.IDSP);
                        product.AvailableQuantity -= item.Quantity;
                        productServices.UpdateProduct(product);
                    }
                    TempData["successful"] = "Thanh toán thanh toán thành công";
                    return RedirectToAction("ShowCart", "Cart");
                }
                else
                {
                    TempData["PayError"] = "Thanh toán không thành công do số lượng tồn của " + Chuoi + " không đủ !!!";

                }
            }
            return RedirectToAction("ShowCartUser", "Cart");
        }
        public IActionResult ShowListBill()
        {
            List<User> lstuser = new List<User>();
            lstuser = userServices.GetAllUsers();
            ViewData["User"] = new SelectList(lstuser, "UserID", "Username");
            var bill = billServices.GetAllBills();
            return View(bill);
        }
    }
}

Assignment_thinhvdph26886/Controllers/ProductController.cs
using Assignment_thinhvdph26886.IServices;
using Assignment_thinhvdph26886.Models;
using Assignment_thinhvdph26886.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Assignment_thinhvdph26886.Controllers
{
    public class ProductController : Controller
    {
        private readonly ILogger<ProductController> _logger;
        private readonly IProductServices _productServices;
        private readonly ShoppingDbContext _context;

        public ProductController(ILogger<ProductController> logger)
        {
            _logger = logger;
            _productServices = new ProductServices();
            _context = new ShoppingDbContext();
        }
        public IActionResult ShowAss()
        {
            var products = _productServices.GetProductsLinq();
            return View(products);
        }
        public IActionResult ShowListProduct()
        {
            var products = _productServices.GetAllProducts();
            return View(products);
        }
        public IActionResult ShowListProductKH()
        {
            var products = _productServices.GetAllProducts();
            return View(products);
        }
        public IActionResult ShowList()
        {
            var products = _productServices.GetAllProducts();
            return View(products);
        }
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Product p, IFormFile imageFile)
        {
            if (imageFile != null && imageFile.Length > 0) //Kiểm tra đường dẫn phù hợp
            {
                //Thực hiện sao chếp ảnh đó vào wwwroot
                //Tạo đường dẫn tới thư mục sao chép(nằm trong root)
                var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot",
                    "images", imageFile.FileName); //vd: abc/wwwroot/iamges/xxx.png
                var stream = new FileStream(path, FileMode.Create); //Tạo 1 File Stream để tạo mới
                imageFile.CopyTo(stream); // Copy ảnh đc chịn vào stream đó.
                //Gán lại giá trị link ảnh (lúc này đã nằm trong root cho thuộc tính description)
                p.Description = imageFile.FileName;
            }
            _productServices.CreateProduct(p);
            return RedirectToAction("ShowListProduct");
        }
        public IActionResult Edit(Guid id)
        {

            return View(_productServices.GetProductById(id));
        }
        [HttpPost]
        
        public IActionResult Edit(Product p)
        {
            //var product = _productServices.GetProductById(p.ID);
            //if (p.AvailableQuantity >= 0 && p.Description != "" && p.Price > product.Price)
            //{
            //    product.Name = p.Name;
            //    product.Price = p.Price;
            //    product.AvailableQuantity = p.AvailableQuantity;
            //    product.Status = p.Status;
            //    product.Supplier = p.Supplier;
            //    product.Description = p.Description;
            //    product.Color=p.Color;
            //    _productServices.UpdateProduct(product);
            //    return RedirectToAction("ShowListProduct");
            //}
            //else return Content("Cảnh báo");
            _productServices.UpdateProduct(p);
            return RedirectToAction("ShowListProduct");
        }
        public IActionResult Details(Guid id)
        {
            return View(_productServices.GetProductById(id));
        }
        public IActionResult Delete(Guid id)
        {
            _productServices.DeleteProduct(id);
            return RedirectToAction("ShowListProduct");
        }
        [HttpPost]
        public ViewResult ShowListProductbyName(string title)
        {
            var a = _productServices.GetProductByName(title);
            return View("ShowListProduct", a);
        }
        [HttpPost]
        public ViewResult ShowListProductbyNames(string title)
        {
            var a = _productServices.GetProductByName(title);
            return View("ShowListProductKH", a);
        }
    }
}

Assignment_thinhvdph26886/Controllers/RoleController.cs
using Assignment_thinhvdph26886.IServices;
using Assignment_thinhvdph26886.Models;
using Assignment_thinhvdph26886.Services;
using Microsoft.AspNetCore.Mvc;

namespace Assignment_thinhvdph26886.Controllers
{
    public class RoleController : Controller
    {
        private readonly ILogger<RoleController> _logger;
        private readonly IRoleServices _roleServices;

        public RoleController(ILogger<RoleController> logger)
        {
            _logger = logger;
            _roleServices = new RoleServices();
        }
        public IActionResult ShowListRole()
        {
            var products = _roleServices.GetAllRoles();
            return View(products);
        }
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Role r)
        {
            _roleServices.CreateRole(r);
            return RedirectToAction("ShowListRole");
        }
        public IActionResult Edit(Guid id)
        {
            return View(_roleServices.GetRoleById(id));
        }
        [HttpPost]

        public IActionResult Edit(Role r)
        {
            _roleServices.UpdateRole(r);
            return RedirectToAction("ShowListRole");
        }
        public IActionResult Details(Guid id)
        {
            return View(_roleServices.GetRoleById(id));
        }
        public IActionResult Delete(Guid id)
        {
            _roleServices.DeleteRole(id);
            return RedirectToAction("ShowListRole");
        }
    }
}

Assignment_thinhvdph26886/Views/Shared/_Layout.cshtml
@inject IHttpContextAccessor http

@{
    string role = http.HttpContext.Session.GetString("role");

}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Assignment_thinhvdph26886</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Assignment_thinhvdph26886.styles.css" asp-append-version="true" />
    <link href="~/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/css/checkout.css" rel="stylesheet" />
    <link href="~/css/creditly.css" rel="stylesheet" />
    <link href="~/css/easy-responsive-tabs.css" rel="stylesheet" />
    <link href="~/css/flexslider.css" rel="stylesheet" />
    <link href="~/css/fontawesome-all.min.css" rel="stylesheet" />
    <link href="~/css/jquery-ui1.css" rel="stylesheet" />
    <link href="~/css/shop.css" rel="stylesheet" />
    <link href="~/css/site.css" rel="stylesheet" />
    <link href="~/css/style.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AssFinal2.styles.css" asp-append-version="true" />
              <script>
         addEventListener("load", function () {
             setTimeout(hideURLbar, 0);
         }, false);

         function hideURLbar() {
             window.scrollTo(0, 1);
         }
</script>
    <!--//meta tags ends here-->
    <!--booststrap-->
    <link href="css/bootstrap.min.css" rel="stylesheet" type="text/css" media="all">
    <!--//booststrap end-->
    <!-- font-awesome icons -->
    <link href="css/fontawesome-all.min.css" rel="stylesheet" type="text/css" media="all">
    <!-- //font-awesome icons -->
    <!-- For Clients slider -->
    <link rel="stylesheet" href="css/flexslider.css" type="text/css" media="all" />
    <!--flexs slider-->
    <link href="css/JiSlider.css" rel="stylesheet">
    <!--Shoping cart-->
    <link rel="stylesheet" href="css/shop.css" type="text/css" />
    <!--//Shoping cart-->
    <!--stylesheets-->
    <link href="css/style.css" rel='stylesheet' type='text/css' media="all">
    <!--//stylesheets-->
    <link href="//fonts.googleapis.com/css?family=Sunflower:500,700" rel="stylesheet">
    <link href="//fonts.googleapis.com/css?family=Open+Sans:400,600,700" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/images/b1.jpg" width=100px />
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">HOME</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="about">ABOUT</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="LoginGPT">LOGIN</a>
                        </li>
@*                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="ShowListProductKH">PRODUCTS</a>
                            </li>*@
@*                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="ShowAss">ShowAss</a>
                        </li>*@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="ShowListProduct">LIST PRODUCTS</a>
                        </li>
                       @if (role == "Quản lý")
                        {

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="ShowListUser">USER</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="ShowListRole">ROLE</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Bill" asp-action="ShowListBill">BILLS</a>
                        </li>
                        }
                    </ul>

                    <div class="d-flex align-items-center">

                    @*<div class="input-group rounded">
                        <input type="search" class="form-control rounded" placeholder="Search" aria-label="Search"
                            aria-describedby="search-addon" />
                        </div>*@
                        
                        <a class="nav-link text-dark" asp-area="" asp-controller="Cart" asp-action="ShowCart">
                            <svg style="margin-left:30px" xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-cart4" viewBox="0 0 16 16">
                          <path d="M0 2.5A.5.5 0 0 1 .5 2H2a.5.5 0 0 1 .485.379L2.89 4H14.5a.5.5 0 0 1 .485.621l-1.5 6A.5.5 0 0 1 13 11H4a.5.5 0 0 1-.485-.379L1.61 3H.5a.5.5 0 0 1-.5-.5zM3.14 5l.5 2H5V5H3.14zM6 5v2h2V5H6zm3 0v2h2V5H9zm3 0v2h1.36l.5-2H12zm1.11 3H12v2h.61l.5-2zM11 8H9v2h2V8zM8 8H6v2h2V8zM5 8H3.89l.5 2H5V8zm0 5a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0zm9-1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0z"/>  
                        </svg>
                        </a>
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Login">
                            <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
                              <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
                              <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
                            </svg>
                        </a>
            
                    </div>
                </div>
            </div>
        </nav>
        
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="py-lg-4 py-md-3 py-sm-3 py-3 text-center">
        <div class="copy-agile-right">
            <p>
                © 2018 Toys-Shop. All Rights Reserved | Design by <a href="https://www.instagram.com/vdt_2208/" target="_blank">vdt_2208</a>
            </p>
        </div>
    </footer>
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Login</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="register-form">
                        <form action="#" method="post">
                            <div class="fields-grid">
                                <div class="styled-input">
                                    <input type="text" placeholder="Your Name" name="Your Name" required="">
                                </div>
                                <div class="styled-input">
                                    <input type="email" placeholder="Your Email" name="Your Email" required="">
                                </div>
                                <div class="styled-input">
                                    <input type="password" placeholder="password" name="password" required="">
                                </div>
                                <button type="submit" class="btn subscrib-btnn">Login</button>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
    <!-- //Modal 1-->
    <!--js working-->
    <script src='js/jquery-2.2.3.min.js'></script>
    <!--//js working-->
    <!-- cart-js -->
    <script src="js/minicart.js"></script>
    <script>
        toys.render();

        toys.cart.on('toys_checkout', function (evt) {
            var items, len, i;

            if (this.subtotal() > 0) {
                items = this.items();

                for (i = 0, len = items.length; i < len; i++) { }
            }
        });
    </script>
    <!-- //cart-js -->
    <!--responsiveslides banner-->
    <script src="js/responsiveslides.min.js"></script>
    <script>
        // You can also use "$(window).load(function() {"
        $(function () {
            // Slideshow 4
            $("#slider4").responsiveSlides({
                auto: true,
                pager: false,
                nav: true,
                speed: 900,
                namespace: "callbacks",
                before: function () {
                    $('.events').append("<li>before event fired.</li>");
                },
                after: function () {
                    $('.events').append("<li>after event fired.</li>");
                }
            });

        });
    </script>
    <!--// responsiveslides banner-->
    <!--slider flexisel -->
    <script src="js/jquery.flexisel.js"></script>
    <script>
        $(window).load(function () {
            $("#flexiselDemo1").flexisel({
                visibleItems: 3,
                animationSpeed: 3000,
                autoPlay: true,
                autoPlaySpeed: 2000,
                pauseOnHover: true,
                enableResponsiveBreakpoints: true,
                responsiveBreakpoints: {
                    portrait: {
                        changePoint: 480,
                        visibleItems: 1
                    },
                    landscape: {
                        changePoint: 640,
                        visibleItems: 2
                    },
                    tablet: {
                        changePoint: 768,
                        visibleItems: 2
                    }
                }
            });

        });
    </script>
    <!-- //slider flexisel -->
    <!-- start-smoth-scrolling -->
    <script src="js/move-top.js"></script>
    <script src="js/easing.js"></script>
    <script>
        jQuery(document).ready(function ($) {
            $(".scroll").click(function (event) {
                event.preventDefault();
                $('html,body').animate({
                    scrollTop: $(this.hash).offset().top
                }, 900);
            });
        });
    </script>
    <!-- start-smoth-scrolling -->
    <!-- here stars scrolling icon -->
    <!-------->
    <script>
        $(document).ready(function () {

            var defaults = {
                containerID: 'toTop', // fading element id
                containerHoverID: 'toTopHover', // fading element hover id
                scrollSpeed: 1200,
                easingType: 'linear'
            };
            $().UItoTop({
                easingType: 'easeOutQuart'
            });

        });
    </script>
    <!--bootstrap working-->
    <script src="js/bootstrap.min.js"></script>
    <!-- //bootstrap working-->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>